FROM golang:latest 

WORKDIR /app
ARG GOPROXY
ENV GOPROXY=${GOPROXY}

# Copy module files and download deps
COPY ./go.mod ./go.sum ./
RUN go mod download
# Copy application sources into /app
COPY ./ ./
# Generate the GraphQL server code
# RUN go run github.com/99designs/gqlgen generate

EXPOSE 8080
ENTRYPOINT ["sh", "-c", "go run github.com/99designs/gqlgen generate && go run server.go"]
