package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"app/graph/model"
	"context"

	"gorm.io/gorm/clause"
)

// DocumentID is the resolver for the document_id field.
func (r *documentResolver) DocumentID(ctx context.Context, obj *model.Document) (string, error) {
	document_id := obj.DocumentID.String()
	return document_id, nil
}

// PageCount is the resolver for the page_count field.
func (r *documentResolver) PageCount(ctx context.Context, obj *model.Document) (*int32, error) {
	if obj.PageCount == nil {
		return nil, nil
	}
	count := int32(*obj.PageCount)
	return &count, nil
}

// CreatedAt is the resolver for the created_at field.
func (r *documentResolver) CreatedAt(ctx context.Context, obj *model.Document) (*string, error) {
	created_at := obj.CreatedAt.String()
	return &created_at, nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *documentResolver) UpdatedAt(ctx context.Context, obj *model.Document) (*string, error) {
	updated_at := obj.UpdatedAt.String()
	return &updated_at, nil
}

// AddDocument is the resolver for the addDocument field.
func (r *mutationResolver) AddDocument(ctx context.Context, input model.NewDocument) (*string, error) {
	document := model.Document{
		OriginalFilename: &input.FileName,
		FileLocation:     &input.FPath,
		ClmNbr:           &input.ClaimNum,
		CaseNumber:       input.CaseNum,
	}
	if err := r.DB.Clauses(clause.Returning{}).Create(&document).Error; err != nil {
		return nil, err
	}
	documentID := document.DocumentID.String()
	return &documentID, nil
}

// GetDocuments is the resolver for the getDocuments field.
func (r *queryResolver) GetDocuments(ctx context.Context) ([]*model.Document, error) {
	var documents []*model.Document
	if err := r.DB.Find(&documents).Error; err != nil {
		return nil, err
	}
	return documents, nil
}

// GetDocumentByID is the resolver for the getDocumentByID field.
func (r *queryResolver) GetDocumentByID(ctx context.Context, id *string) (*model.Document, error) {
	document := &model.Document{}
	if err := r.DB.Where("document_id = ?", *id).First(document).Error; err != nil {
		return nil, err
	}
	return document, nil
}

// Document returns DocumentResolver implementation.
func (r *Resolver) Document() DocumentResolver { return &documentResolver{r} }

type documentResolver struct{ *Resolver }
