package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"app/core"
	"app/graph/generated"
	"app/graph/model"
	"context"

	"golang.org/x/crypto/bcrypt"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, user model.CreateUser) (*model.UserResult, error) {
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(user.Password), bcrypt.DefaultCost)
	if err != nil {
		errMsg := err.Error()
		return &model.UserResult{
			Success: false,
			Errors:  []*string{&errMsg},
			Data:    nil,
		}, err
	}

	userModel := &model.User{
		Email:    user.Email,
		Password: string(hashedPassword),
		Role:     string(user.Role),
	}
	result := r.DB.Create(userModel)
	if result.Error != nil {
		errMsg := result.Error.Error()
		return &model.UserResult{
			Success: false,
			Errors:  []*string{&errMsg},
			Data:    nil,
		}, result.Error
	}
	return &model.UserResult{
		Success: true,
		Errors:  []*string{},
		Data:    userModel,
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*model.UserResult, error) {
	user := &model.User{}
	result := r.DB.First(user, id)
	if result.Error != nil {
		errMsg := result.Error.Error()
		return &model.UserResult{
			Success: false,
			Errors:  []*string{&errMsg},
			Data:    nil,
		}, result.Error
	}

	deleteResult := r.DB.Delete(user)
	if deleteResult.Error != nil {
		errMsg := deleteResult.Error.Error()
		return &model.UserResult{
			Success: false,
			Errors:  []*string{&errMsg},
			Data:    nil,
		}, deleteResult.Error
	}

	return &model.UserResult{
		Success: true,
		Errors:  []*string{},
		Data:    user,
	}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, user *model.UpdateUser) (*model.UserResult, error) {
	userModel := &model.User{}
	result := r.DB.First(userModel, user.ID)
	if result.Error != nil {
		errMsg := result.Error.Error()
		return &model.UserResult{
			Success: false,
			Errors:  []*string{&errMsg},
			Data:    nil,
		}, result.Error
	}

	if user.Email != nil {
		userModel.Email = *user.Email
	}
	if user.Password != nil {
		hashedPassword, err := bcrypt.GenerateFromPassword([]byte(*user.Password), bcrypt.DefaultCost)
		if err != nil {
			errMsg := err.Error()
			return &model.UserResult{
				Success: false,
				Errors:  []*string{&errMsg},
				Data:    nil,
			}, err
		}
		userModel.Password = string(hashedPassword)
	}
	if user.Role != nil {
		userModel.Role = string(*user.Role)
	}

	saveResult := r.DB.Save(userModel)
	if saveResult.Error != nil {
		errMsg := saveResult.Error.Error()
		return &model.UserResult{
			Success: false,
			Errors:  []*string{&errMsg},
			Data:    nil,
		}, saveResult.Error
	}

	return &model.UserResult{
		Success: true,
		Errors:  []*string{},
		Data:    userModel,
	}, nil
}

// User is the resolver for the User field.
func (r *queryResolver) User(ctx context.Context, query *model.UsersQuery) (*model.UsersResult, error) {
	userModel := []*model.User{}
	results := r.DB.Find(&userModel)
	if results.Error != nil {
		errMsg := results.Error.Error()
		return &model.UsersResult{
			Success: false,
			Errors:  []*string{&errMsg},
			Data:    nil,
		}, results.Error
	}

	return &model.UsersResult{
		Success: true,
		Errors:  []*string{},
		Data:    userModel,
	}, nil
}

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, query *model.LoginInput) (*model.LoginOutput, error) {
	user := &model.User{}
	result := r.DB.Where("email = ?", query.Email).First(user)
	if result.Error != nil {
		errMsg := "Wrong user"
		return &model.LoginOutput{
			Success: false,
			Error:   &errMsg,
			Data:    nil,
		}, nil
	}

	if err := bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(query.Password)); err != nil {
		errMsg := "Wrong Password"
		return &model.LoginOutput{
			Success: false,
			Error:   &errMsg,
			Data:    nil,
		}, nil
	}

	return &model.LoginOutput{
		Success: true,
		Error:   nil,
		Data:    user,
	}, nil
}

// Test is the resolver for the test field.
func (r *queryResolver) Test(ctx context.Context, id *int, url *string) (*string, error) {
	core.DownloadAudioFromYouTube(r.DB, ctx, int(*id), *url)
	msg := "Test successful"
	return &msg, nil
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *model.User) (string, error) {
	return obj.ID.String(), nil
}

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *model.User) (model.UserTypes, error) {
	return model.UserTypes(obj.Role), nil
}

// CreatedAt is the resolver for the created_at field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *model.User) (string, error) {
	return obj.CreatedAt.Format("2006-01-02 15:04:05"), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
