package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"app/core"
	"app/graph/model"
	"app/new_helper_functions"
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"gorm.io/gorm/clause"
)

// CreateNewPureSong is the resolver for the createNewPureSong field.
func (r *mutationResolver) CreateNewPureSong(ctx context.Context, song *model.CreatePureSong) (*model.PureSongResult, error) {
	newSong := &model.Song{
		Title:      song.Title,
		Release:    *song.Release,
		ArtistName: song.ArtistName,
		Year:       song.Year,
		VideoLink:  *song.VideoLink,
	}
	db := r.DB.Clauses(clause.Returning{}).Create(newSong)
	if db.Error != nil {
		errMsg := db.Error.Error()
		return &model.PureSongResult{
			Success: false,
			Errors:  []*string{&errMsg},
			Data:    nil,
		}, db.Error
	}
	if newSong.SongID != 0 {
		local_link, err := core.DownloadAudioFromYouTube(r.DB, ctx, newSong.SongID, *song.VideoLink)
		if err != nil {
			errMsg := err.Error()
			return &model.PureSongResult{
				Success: false,
				Errors:  []*string{&errMsg},
				Data:    nil,
			}, err
		}
		newSong.LocalLink = local_link
		saveResult := r.DB.Save(newSong)
		if saveResult.Error != nil {
			errMsg := saveResult.Error.Error()
			return &model.PureSongResult{
				Success: false,
				Errors:  []*string{&errMsg},
				Data:    nil,
			}, saveResult.Error
		}
	}
	return &model.PureSongResult{
		Success: true,
		Errors:  []*string{},
		Data:    newSong,
	}, nil
}

// UpdatePureSong is the resolver for the updatePureSong field.
func (r *mutationResolver) UpdatePureSong(ctx context.Context, song model.UpdatePureSong) (*model.PureSongResult, error) {
	songModel := &model.Song{}
	result := r.DB.First(songModel, song.ID)
	if result.Error != nil {
		errMsg := result.Error.Error()
		return &model.PureSongResult{
			Success: false,
			Errors:  []*string{&errMsg},
			Data:    nil,
		}, result.Error
	}

	if song.Title != nil {
		songModel.Title = *song.Title
	}
	if song.Release != nil {
		songModel.Release = *song.Release
	}
	if song.ArtistName != nil {
		songModel.ArtistName = *song.ArtistName
	}
	if song.Year != nil {
		songModel.Year = *song.Year
	}
	if song.VideoLink != nil {
		songModel.VideoLink = *song.VideoLink
	}

	saveResult := r.DB.Save(songModel)
	if saveResult.Error != nil {
		errMsg := saveResult.Error.Error()
		return &model.PureSongResult{
			Success: false,
			Errors:  []*string{&errMsg},
			Data:    nil,
		}, saveResult.Error
	}

	return &model.PureSongResult{
		Success: true,
		Errors:  []*string{},
		Data:    songModel,
	}, nil
}

// ListPureSongs is the resolver for the listPureSongs field.
func (r *queryResolver) ListPureSongs(ctx context.Context, filters model.PureSongFilters) (*model.PureSongsResult, error) {
	songs := []*model.Song{}
	query := r.DB.Model(&model.Song{})
	fields := graphql.CollectFieldsCtx(ctx, nil)
	selectedFields := new_helper_functions.OnlyFieldNames(fields)

	switch filters.Filter {
	case "title":
		query.Where("title ILIKE ?", "%"+*filters.Search+"%")
	case "release":
		query.Where("release=?", filters.Search)
	case "artist_name":
		query.Where("artist_name ILIKE ?", "%"+*filters.Search+"%")
	case "year":
		query.Where("year=?", filters.Search)
	case "video_link":
		query.Where("video_link=?", filters.Search)
	}

	result := query.Select(selectedFields).Find(&songs)
	if result.Error != nil {
		errMsg := result.Error.Error()
		return &model.PureSongsResult{
			Success: false,
			Errors:  []*string{&errMsg},
			Data:    []*model.Song{},
		}, result.Error
	}

	return &model.PureSongsResult{
		Success: true,
		Errors:  []*string{},
		Data:    songs,
	}, nil
}

// DownloadSong is the resolver for the downloadSong field.
func (r *queryResolver) DownloadSong(ctx context.Context, id string) (*string, error) {
	song := &model.Song{}
	result := r.DB.Select("local_link").Where("song_id=?", id).First(song)
	if result.Error != nil {
		return nil, result.Error
	}

	downloadLink := "/downloads/" + song.LocalLink
	return &downloadLink, nil
}

// SearchSong is the resolver for the searchSong field.
func (r *queryResolver) SearchSong(ctx context.Context, songText string, model *string) ([]*int, error) {
	panic(fmt.Errorf("not implemented: SearchSong - searchSong"))
}

// RetrainChroma is the resolver for the retrainChroma field.
func (r *queryResolver) RetrainChroma(ctx context.Context, name *string, chank *int, overlap *int) (string, error) {
	panic(fmt.Errorf("not implemented: RetrainChroma - retrainChroma"))
}

// ResetChroma is the resolver for the resetChroma field.
func (r *queryResolver) ResetChroma(ctx context.Context, name string) (string, error) {
	panic(fmt.Errorf("not implemented: ResetChroma - resetChroma"))
}
