package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"app/ai_functions"
	"app/core"
	"app/graph/model"
	"app/new_helper_functions"
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/99designs/gqlgen/graphql"
	"gorm.io/gorm"
)

// ChangeCount is the resolver for the changeCount field.
func (r *mutationResolver) ChangeCount(ctx context.Context, input model.UserSongCountInput) (int, error) {
	songModel := &model.Songs{}
	result := r.DB.Where("user_id=? AND song_id=?", input.UserID, input.SongID).First(songModel)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return 0, fmt.Errorf("song not found for user")
		}
		return 0, fmt.Errorf("database query failed: %s", result.Error.Error())
	}
	currentCount := songModel.PlayCount
	songModel.PlayCount = currentCount + 1
	err := r.DB.Save(songModel).Error
	if err != nil {
		return 0, fmt.Errorf("failed to update play count: %s", err.Error())
	}
	return songModel.ID, nil
}

// CreateSong is the resolver for the createSong field.
func (r *mutationResolver) CreateSong(ctx context.Context, song model.CreateSong) (*model.SongResult, error) {
	songmodel := &model.Songs{}
	result := r.DB.Where("user_id = ? AND song_id = ?", song.UserID, song.SongID).First(songmodel)
	fmt.Println("Result of query: ", result.Error, " RowsAffected: ", result.RowsAffected)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			fmt.Println("Creating new song")
			var release, link string
			if song.Release != nil {
				release = *song.Release
			}
			if song.LocalLink != nil {
				link = *song.LocalLink
			}
			playCount := 0
			if song.PlayCount != nil {
				playCount = *song.PlayCount
			}
			newSong := &model.Songs{
				UserID:     song.UserID,
				SongID:     song.SongID,
				PlayCount:  playCount,
				Title:      song.Title,
				Release:    release,
				ArtistName: song.ArtistName,
				Year:       song.Year,
				LocalLink:  link,
			}
			r.DB.Save(&newSong)
			return &model.SongResult{
				Success: true,
				Errors:  []*string{},
				Data:    newSong,
			}, nil
		}
		errorMessage := result.Error.Error()
		return &model.SongResult{
			Success: false,
			Errors:  []*string{&errorMessage},
			Data:    nil,
		}, nil
	}

	errMsg := "already has a song"
	return &model.SongResult{
		Success: false,
		Errors:  []*string{&errMsg},
		Data:    nil,
	}, nil
}

// UpdateSong is the resolver for the updateSong field.
func (r *mutationResolver) UpdateSong(ctx context.Context, song model.UpdateSong) (*model.SongResult, error) {
	songmodel := &model.Songs{}
	result := r.DB.Where("id=?", song.ID).First(songmodel)
	if result.Error != nil {
		errorMessage := result.Error.Error()
		return &model.SongResult{
			Success: false,
			Errors:  []*string{&errorMessage},
			Data:    nil,
		}, nil
	}
	if songmodel == nil {
		errMsg := "song not found"
		return &model.SongResult{
			Success: false,
			Errors:  []*string{&errMsg},
			Data:    nil,
		}, nil
	}
	if song.PlayCount != nil {
		songmodel.PlayCount = *song.PlayCount
	}
	if song.Title != nil {
		songmodel.Title = *song.Title
	}
	if song.Release != nil {
		songmodel.Release = *song.Release
	}
	if song.ArtistName != nil {
		songmodel.ArtistName = *song.ArtistName
	}
	if song.Year != nil {
		songmodel.Year = *song.Year
	}
	if song.LocalLink != nil {
		songmodel.LocalLink = *song.LocalLink
	}
	r.DB.Save(songmodel)
	return &model.SongResult{
		Success: true,
		Errors:  []*string{},
		Data:    songmodel,
	}, nil
}

// UpdateAllSongLinks is the resolver for the updateAllSongLinks field.
func (r *mutationResolver) UpdateAllSongLinks(ctx context.Context, song *model.UpdateAllSongLinksInput) (*model.UpdateAllSongsType, error) {
	id := song.ID
	link := song.LocalLink
	findSong := model.Song{}
	// 1. Execute the query and capture the result metadata
	result := r.DB.Where("song_id = ?", id).Find(&findSong)
	if result.Error != nil {
		return nil, fmt.Errorf("database query failed: %w", result.Error)
	}
	if result.RowsAffected == 0 {
		return nil, fmt.Errorf("song not found")
	}
	if findSong.LocalLink == "" {
		fmt.Println(link)
		localLink, err := core.DownloadAudioFromYouTube(r.DB, ctx, findSong.SongID, link)
		if err != nil {
			return nil, fmt.Errorf("failed to download audio from YouTube: %w", err)
		}
		findSong.LocalLink = localLink
	}
	// 2. Update all records with the same song_id
	updateResult := r.DB.Model(&model.Songs{}).Where("song_id = ?", id).Updates(map[string]interface{}{
		"local_link": findSong.LocalLink,
	})
	if updateResult.Error != nil {
		return nil, fmt.Errorf("failed to update song links: %w", updateResult.Error)
	}

	return &model.UpdateAllSongsType{
		Success:   true,
		Errors:    []*string{},
		Ids:       []*int{&id},
		LocalLink: &findSong.LocalLink,
	}, nil
}

// ListSongs is the resolver for the listSongs field.
func (r *queryResolver) ListSongs(ctx context.Context, filters model.SongFilters) (*model.SongsResult, error) {
	songs := []*model.Songs{}
	query := r.DB.Model(&model.Songs{})
	fields := graphql.CollectFieldsCtx(ctx, nil)
	selectedFields := new_helper_functions.OnlyFieldNames(fields)
	if filters.Search != nil && *filters.Search != "" {
		switch filters.Filter {
		case "title":
			query = query.Where("title ILIKE ?", "%"+*filters.Search+"%")
		case "release":
			query = query.Where("release=?", filters.Search)
		case "artist":
			query = query.Where("artist_name ILIKE ?", "%"+*filters.Search+"%")
		case "year":
			query = query.Where("year=?", filters.Search)
		case "link":
			query = query.Where("link=?", filters.Search)
		}
	}
	if filters.User != nil && *filters.User != "" {
		query = query.Where("user_id=?", *filters.User)
	}
	if filters.Offset == nil {
		query = query.Offset(0)
	} else {
		query = query.Offset(*filters.Offset)
	}
	if filters.Limit == nil {
		query = query.Limit(10)
	} else {
		query = query.Limit(*filters.Limit)
	}
	query = query.Group("song_id, id").Order("play_count DESC")
	query = query.Select(selectedFields)
	query = query.Debug()
	fmt.Println("Executing query:", query.Statement.SQL.String())

	query.Find(&songs)
	println("Retrieved songs:", len(songs))

	for _, song := range songs {
		fmt.Printf("Song: %+v\n", song)
		println("ID:", song.SongID, "Song ID:", song.SongID, "Link:", song.LocalLink)
	}
	return &model.SongsResult{
		Success: true,
		Errors:  []*string{},
		Data:    songs,
	}, nil
}

// GetSong is the resolver for the getSong field.
func (r *queryResolver) GetSong(ctx context.Context, id string) (*model.SongResult, error) {
	song := &model.Songs{}
	result := r.DB.Where("song_id=?", id).First(song)
	if result.Error != nil {
		errMsg := result.Error.Error()
		errMsgPtr := errMsg
		return &model.SongResult{
			Success: false,
			Errors:  []*string{&errMsgPtr},
			Data:    nil,
		}, nil
	}
	return &model.SongResult{
		Success: true,
		Errors:  []*string{},
		Data:    song,
	}, nil
}

// PredictSong is the resolver for the predictSong field.
func (r *queryResolver) PredictSong(ctx context.Context, query model.SongInput) (*model.PredictOutput, error) {
	rows, err := r.DB.Model(&model.Songs{}).Select("user_id, song_id, play_count").Rows()

	if err != nil {
		errMsg := err.Error()
		return &model.PredictOutput{
			Success: false,
			Errors:  []*string{&errMsg},
			Data:    nil,
		}, nil
	}
	defer rows.Close()
	var dataset []ai_functions.SongRating
	for rows.Next() {
		var sr ai_functions.SongRating
		var rowPlayCount float64
		if err := rows.Scan(&sr.UserID, &sr.SongID, &rowPlayCount); err != nil {
			errMsg := err.Error()
			errMsgPtr := errMsg
			return &model.PredictOutput{Success: false, Errors: []*string{&errMsgPtr}, Data: nil}, nil
		}
		sr.Score = math.Min(rowPlayCount, 5.0)
		dataset = append(dataset, sr)
	}
	predictions, err := ai_functions.GetRecommendations(dataset, query.UserID.String(), 3)
	fmt.Println("predictions", predictions)
	if err != nil {
		errMsg := err.Error()
		errMsgPtr := errMsg
		return &model.PredictOutput{Success: false, Errors: []*string{&errMsgPtr}, Data: nil}, nil
	}
	var gqlPredictions []*model.Prediction
	for _, p := range predictions {
		fmt.Println(p)
		common := p.Common
		score := p.Score
		id := p.ID

		gqlPredictions = append(gqlPredictions, &model.Prediction{
			ID:     &id,
			Score:  &score,
			Common: &common,
		})
	}
	return &model.PredictOutput{
		Success: true,
		Errors:  []*string{},
		Data:    gqlPredictions,
	}, nil
}
