package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"app/graph/model"
	"context"
	"fmt"

	"gorm.io/gorm/clause"
)

// CreateStudent is the resolver for the createStudent field.
func (r *mutationResolver) CreateStudent(ctx context.Context, input model.StudentInput) (*model.Student, error) {
	student := model.Student{
		ID:        0, // ID will be set by the database
		FirstName: &input.FirstName,
		LastName:  &input.LastName,
		Number:    input.Number,
	}
	// Here, you would typically save the student to your database.
	// For demonstration purposes, we'll just return the student with a mock ID.
	if err := r.DB.Clauses(clause.Returning{}).Create(&student).Error; err != nil {
		return nil, err
	}
	return &student, nil
}

// GetStudents is the resolver for the getStudents field.
func (r *queryResolver) GetStudents(ctx context.Context) ([]*model.Student, error) {
	panic(fmt.Errorf("not implemented: GetStudents - getStudents"))
}

// ID is the resolver for the ID field.
func (r *studentResolver) ID(ctx context.Context, obj *model.Student) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// Student returns StudentResolver implementation.
func (r *Resolver) Student() StudentResolver { return &studentResolver{r} }

type studentResolver struct{ *Resolver }
