package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"app/graph/model"
	"context"
	"fmt"

	"gorm.io/gorm/clause"
)

// CreateZurichTeam is the resolver for the createZurichTeam field.
func (r *mutationResolver) CreateZurichTeam(ctx context.Context, name string) (*model.ZurichTeam, error) {
	team := model.ZurichTeam{
		Name: &name,
	}
	if err := r.DB.Clauses(clause.Returning{}).Create(&team).Error; err != nil {
		return nil, err
	}
	return &team, nil
}

// GetZurichTeams is the resolver for the getZurichTeams field.
func (r *queryResolver) GetZurichTeams(ctx context.Context) ([]*model.ZurichTeam, error) {
	panic(fmt.Errorf("not implemented: GetZurichTeams - getZurichTeams"))
}

// ID is the resolver for the ID field.
func (r *zurichTeamResolver) ID(ctx context.Context, obj *model.ZurichTeam) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
	//panic(fmt.Errorf("not implemented: ID - ID"))
}

// ZurichTeam returns ZurichTeamResolver implementation.
func (r *Resolver) ZurichTeam() ZurichTeamResolver { return &zurichTeamResolver{r} }

type zurichTeamResolver struct{ *Resolver }
