// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewUser struct {
	Name string `json:"name"`
}

type Query struct {
}

type StudentInput struct {
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Number    *string `json:"number,omitempty"`
}

type User struct {
	ID   string  `json:"ID"`
	Name *string `json:"name,omitempty"`
}

type NewDocument struct {
	FileName string  `json:"file_name"`
	FPath    string  `json:"f_path"`
	ClaimNum string  `json:"claim_num"`
	CaseNum  *string `json:"case_num,omitempty"`
}
