// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/google/uuid"
)

type Mutation struct {
}

type Query struct {
}

type UserContext struct {
	UserID     uuid.UUID `json:"userID"`
	Rank       int       `json:"rank"`
	UserName   string    `json:"userName"`
	UserEmail  string    `json:"userEmail"`
	UserRole   UserTypes `json:"userRole"`
	UserOffice string    `json:"userOffice"`
	UserLob    string    `json:"userLOB"`
	UserGroups []int     `json:"userGroups"`
}

type UserResult struct {
	Success bool      `json:"success"`
	Errors  []*string `json:"errors,omitempty"`
	Data    *User     `json:"data,omitempty"`
}

type UsersQuery struct {
	Limit  *int    `json:"limit,omitempty"`
	Offset *int    `json:"offset,omitempty"`
	Search *string `json:"search,omitempty"`
	ID     *string `json:"id,omitempty"`
}

type UsersResult struct {
	Success bool      `json:"success"`
	Errors  []*string `json:"errors,omitempty"`
	Data    []*User   `json:"data,omitempty"`
}

type CreatePureSong struct {
	Title      string  `json:"title"`
	Release    *string `json:"release,omitempty"`
	ArtistName string  `json:"artist_name"`
	Link       *string `json:"link,omitempty"`
	Year       int     `json:"year"`
}

type CreateSong struct {
	UserID     uuid.UUID `json:"user_id"`
	SongID     int       `json:"song_id"`
	PlayCount  *int      `json:"play_count,omitempty"`
	Title      string    `json:"title"`
	Release    *string   `json:"release,omitempty"`
	ArtistName string    `json:"artist_name"`
	Link       *string   `json:"link,omitempty"`
	Year       int       `json:"year"`
}

type CreateUser struct {
	Email    string    `json:"email"`
	Password string    `json:"password"`
	Role     UserTypes `json:"role"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginOutput struct {
	Success bool    `json:"success"`
	Error   *string `json:"error,omitempty"`
	Data    *User   `json:"data,omitempty"`
}

type PredictOutput struct {
	Success bool          `json:"success"`
	Errors  []*string     `json:"errors,omitempty"`
	Data    []*Prediction `json:"data,omitempty"`
}

type Prediction struct {
	ID     *string  `json:"id,omitempty"`
	Score  *float64 `json:"score,omitempty"`
	Common *bool    `json:"common,omitempty"`
}

type PureSongFilters struct {
	Search *string `json:"search,omitempty"`
	Filter string  `json:"filter"`
	User   *string `json:"user,omitempty"`
	Limit  *int    `json:"limit,omitempty"`
	Offset *int    `json:"offset,omitempty"`
}

type PureSongResult struct {
	Success bool      `json:"success"`
	Errors  []*string `json:"errors,omitempty"`
	Data    *Song     `json:"data,omitempty"`
}

type PureSongsResult struct {
	Success bool      `json:"success"`
	Errors  []*string `json:"errors,omitempty"`
	Data    []*Song   `json:"data,omitempty"`
}

type SongFilters struct {
	Search *string `json:"search,omitempty"`
	Filter string  `json:"filter"`
	User   *string `json:"user,omitempty"`
	Limit  *int    `json:"limit,omitempty"`
	Offset *int    `json:"offset,omitempty"`
}

type SongInput struct {
	UserID uuid.UUID `json:"user_id"`
}

type SongResult struct {
	Success bool      `json:"success"`
	Errors  []*string `json:"errors,omitempty"`
	Data    *Songs    `json:"data,omitempty"`
}

type SongsResult struct {
	Success bool      `json:"success"`
	Errors  []*string `json:"errors,omitempty"`
	Data    []*Songs  `json:"data,omitempty"`
}

type UpdateAllSongLinksInput struct {
	ID   int    `json:"id"`
	Link string `json:"link"`
}

type UpdateAllSongsType struct {
	Success bool      `json:"success"`
	Errors  []*string `json:"errors,omitempty"`
	Ids     []*int    `json:"ids,omitempty"`
}

type UpdatePureSong struct {
	ID         string  `json:"id"`
	Title      *string `json:"title,omitempty"`
	Release    *string `json:"release,omitempty"`
	ArtistName *string `json:"artist_name,omitempty"`
	Link       *string `json:"link,omitempty"`
	Year       *int    `json:"year,omitempty"`
}

type UpdateSong struct {
	ID         *string `json:"id,omitempty"`
	PlayCount  *int    `json:"play_count,omitempty"`
	Title      *string `json:"title,omitempty"`
	Release    *string `json:"release,omitempty"`
	ArtistName *string `json:"artist_name,omitempty"`
	Link       *string `json:"link,omitempty"`
	Year       *int    `json:"year,omitempty"`
}

type UpdateUser struct {
	ID       string     `json:"id"`
	Email    *string    `json:"email,omitempty"`
	Password *string    `json:"password,omitempty"`
	Role     *UserTypes `json:"role,omitempty"`
}

type UserSongCountInput struct {
	SongID int       `json:"song_id"`
	UserID uuid.UUID `json:"user_id"`
}

type UserTypes string

const (
	UserTypesAdmin UserTypes = "ADMIN"
	UserTypesUser  UserTypes = "USER"
)

var AllUserTypes = []UserTypes{
	UserTypesAdmin,
	UserTypesUser,
}

func (e UserTypes) IsValid() bool {
	switch e {
	case UserTypesAdmin, UserTypesUser:
		return true
	}
	return false
}

func (e UserTypes) String() string {
	return string(e)
}

func (e *UserTypes) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserTypes(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserTypes", str)
	}
	return nil
}

func (e UserTypes) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserTypes) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserTypes) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
